/**
* sharednic API
* Sharednic Service
*
* OpenAPI spec version: 2.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/netgroup-polito/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

#include "api/SharednicApiImpl.h"
#define MANAGER_TYPE io::swagger::server::api::SharednicApiImpl
#define SERVICE_DESCRIPTION "Sharednic Service"
#define SERVICE_VERSION "2.0"
#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "polycube/a0059af8c"
#define SERVICE_REQUIRED_KERNEL_VERSION "4.14.0"
const std::string SERVICE_DATA_MODEL = R"POLYCUBE_DM(
module sharednic {
  yang-version 1.1;
  namespace "http://polycube.network/sharednic";
  prefix "sharednic";

  import polycube-base { prefix "basemodel"; }

  organization "Polycube open source project";
  description "YANG data model for the Polycube Sharednic service";

  basemodel:service-description "Sharednic Service";
  basemodel:service-version "2.0";
  basemodel:service-name "sharednic";
  basemodel:service-min-kernel-version "4.14.0";

  uses "basemodel:base-yang-module";

  leaf action {
    type enumeration {
      enum DROP;
      enum LINUX;
      enum POLYCUBE;
    }
    default DROP;
    description "Action performed on the received packet (i.e., DROP, LINUX, or POLYCUBE; default: DROP)";
  }
}

)POLYCUBE_DM";
#include <polycube/services/shared_library.h>
