/**
* sharednic API
* Sharednic Service
*
* OpenAPI spec version: 2.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/netgroup-polito/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

/*
* SharednicInterface.h
*
*
*/

#pragma once

#include "../serializer/SharednicJsonObject.h"

#include "../Ports.h"

using namespace io::swagger::server::model;

class SharednicInterface {
public:

  virtual void update(const SharednicJsonObject &conf) = 0;
  virtual SharednicJsonObject toJsonObject() = 0;

  /// <summary>
  /// Name of the sharednic service
  /// </summary>
  virtual std::string getName() = 0;

  /// <summary>
  /// UUID of the Cube
  /// </summary>
  virtual std::string getUuid() = 0;

  /// <summary>
  /// Type of the Cube (TC, XDP_SKB, XDP_DRV)
  /// </summary>
  virtual CubeType getType() = 0;

  /// <summary>
  /// Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE)
  /// </summary>
  virtual SharednicLoglevelEnum getLoglevel() = 0;
  virtual void setLoglevel(const SharednicLoglevelEnum &value) = 0;

  /// <summary>
  /// Entry of the ports table
  /// </summary>
  virtual std::shared_ptr<Ports> getPorts(const std::string &name) = 0;
  virtual std::vector<std::shared_ptr<Ports>> getPortsList() = 0;
  virtual void addPorts(const std::string &name, const PortsJsonObject &conf) = 0;
  virtual void addPortsList(const std::vector<PortsJsonObject> &conf) = 0;
  virtual void replacePorts(const std::string &name, const PortsJsonObject &conf) = 0;
  virtual void delPorts(const std::string &name) = 0;
  virtual void delPortsList() = 0;

  /// <summary>
  /// Action performed on the received packet (i.e., DROP, LINUX, or POLYCUBE; default: DROP)
  /// </summary>
  virtual SharednicActionEnum getAction() = 0;
  virtual void setAction(const SharednicActionEnum &value) = 0;
};

