/**
* sharednic API
* Sharednic Service
*
* OpenAPI spec version: 2.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/netgroup-polito/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */


#include "SharednicApiImpl.h"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

SharednicApiImpl::SharednicApiImpl() {}

/*
* These functions include a default basic implementation.  The user could
* extend adapt this implementation to his needs.
*/

std::shared_ptr<Sharednic> SharednicApiImpl::get_cube(const std::string &name) {
  std::lock_guard<std::mutex> guard(cubes_mutex);
  auto iter = cubes.find(name);
  if (iter == cubes.end()) {
    throw std::runtime_error("Cube " + name + " does not exist");
  }

  return iter->second;
}

void SharednicApiImpl::create_sharednic_by_id(const std::string &name, const SharednicJsonObject &jsonObject) {
  {
    // check if name is valid before creating it
    std::lock_guard<std::mutex> guard(cubes_mutex);
    if (cubes.count(name) != 0) {
      throw std::runtime_error("There is already an Cube with name " + name);
    }
  }
  auto ptr = std::make_shared<Sharednic>(name, jsonObject, jsonObject.getType());
  std::unordered_map<std::string, std::shared_ptr<Sharednic>>::iterator iter;
  bool inserted;

  std::lock_guard<std::mutex> guard(cubes_mutex);
  std::tie(iter, inserted) = cubes.emplace(name, std::move(ptr));

  if (!inserted) {
    throw std::runtime_error("There is already an Cube with name " + name);
  }
}

void SharednicApiImpl::replace_sharednic_by_id(const std::string &name, const SharednicJsonObject &bridge){
  throw std::runtime_error("Method not supported!");
}

void SharednicApiImpl::delete_sharednic_by_id(const std::string &name) {
  std::lock_guard<std::mutex> guard(cubes_mutex);
  if (cubes.count(name) == 0) {
    throw std::runtime_error("Cube " + name + " does not exist");
  }
  cubes.erase(name);
}

std::string SharednicApiImpl::read_sharednic_uuid_by_id(const std::string &name) {
  auto m = get_cube(name);
  return m->getUuid();
}

std::vector<SharednicJsonObject> SharednicApiImpl::read_sharednic_list_by_id() {
  std::vector<SharednicJsonObject> jsonObject_vect;
  for(auto &i : cubes) {
    auto m = get_cube(i.first);
    jsonObject_vect.push_back(m->toJsonObject());
  }
  return jsonObject_vect;
}

std::vector<nlohmann::fifo_map<std::string, std::string>> SharednicApiImpl::read_sharednic_list_by_id_get_list() {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  for (auto &x : cubes) {
    nlohmann::fifo_map<std::string, std::string> m;
    m["name"] = x.first;
    r.push_back(std::move(m));
  }
  return r;
}

/*
* Ports list related functions
*/
void SharednicApiImpl::create_sharednic_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &ports) {
  auto m = get_cube(name);
  m->addPortsList(ports);
}

std::vector<PortsJsonObject> SharednicApiImpl::read_sharednic_ports_list_by_id(const std::string &name) {
  std::vector<PortsJsonObject> vect;
  auto m = get_cube(name);
  for (auto &i : m->getPortsList()) {
    vect.push_back(i->toJsonObject());
  }
  return vect;
}

void SharednicApiImpl::replace_sharednic_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &ports) {
  throw std::runtime_error("Method not supported");
}

void SharednicApiImpl::delete_sharednic_ports_list_by_id(const std::string &name) {
  auto m = get_cube(name);
  m->delPortsList();
}

std::vector<nlohmann::fifo_map<std::string, std::string>> SharednicApiImpl::read_sharednic_ports_list_by_id_get_list(const std::string &name) {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  auto m = get_cube(name);
  for(auto &i : m->getPortsList()){
    nlohmann::fifo_map<std::string, std::string> m;
    m["name"] = i->getName();
    r.push_back(std::move(m));
  }
  return r;
}

/*
* Ports related functions
*/
void SharednicApiImpl::create_sharednic_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &ports) {
  auto m = get_cube(name);
  return m->addPorts(portsName, ports);
}

PortsJsonObject SharednicApiImpl::read_sharednic_ports_by_id(const std::string &name, const std::string &portsName) {
  auto m = get_cube(name);
  return m->getPorts(portsName)->toJsonObject();
}

void SharednicApiImpl::replace_sharednic_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &ports) {
  auto m = get_cube(name);
  m->replacePorts(portsName, ports);
}

void SharednicApiImpl::delete_sharednic_ports_by_id(const std::string &name, const std::string &portsName) {
  auto m = get_cube(name);
  m->delPorts(portsName);
}

std::string SharednicApiImpl::read_sharednic_ports_peer_by_id(const std::string &name, const std::string &portsName) {
  auto m = get_cube(name);
  auto p = m->getPorts(portsName);
  return p->getPeer();
}

PortsStatusEnum SharednicApiImpl::read_sharednic_ports_status_by_id(const std::string &name, const std::string &portsName) {
  auto m = get_cube(name);
  auto p = m->getPorts(portsName);
  return p->getStatus();
}

std::string SharednicApiImpl::read_sharednic_ports_uuid_by_id(const std::string &name, const std::string &portsName) {
  auto m = get_cube(name);
  auto p = m->getPorts(portsName);
  return p->getUuid();
}

void SharednicApiImpl::update_sharednic_ports_peer_by_id(const std::string &name, const std::string &portsName, const std::string &peer) {
  auto m = get_cube(name);
  auto p = m->getPorts(portsName);
  p->setPeer(peer);
}


/**
* @brief   Read action by ID
*
* Read operation of resource: action*
*
* @param[in] name ID of name
*
* Responses:
* SharednicActionEnum
*/
SharednicActionEnum
SharednicApiImpl::read_sharednic_action_by_id(const std::string &name) {
  auto sharednic = get_cube(name);
  return sharednic->getAction();

}




/**
* @brief   Read sharednic by ID
*
* Read operation of resource: sharednic*
*
* @param[in] name ID of name
*
* Responses:
* SharednicJsonObject
*/
SharednicJsonObject
SharednicApiImpl::read_sharednic_by_id(const std::string &name) {
  return get_cube(name)->toJsonObject();

}




/**
* @brief   Read loglevel by ID
*
* Read operation of resource: loglevel*
*
* @param[in] name ID of name
*
* Responses:
* SharednicLoglevelEnum
*/
SharednicLoglevelEnum
SharednicApiImpl::read_sharednic_loglevel_by_id(const std::string &name) {
  auto sharednic = get_cube(name);
  return sharednic->getLoglevel();

}




/**
* @brief   Read type by ID
*
* Read operation of resource: type*
*
* @param[in] name ID of name
*
* Responses:
* CubeType
*/
CubeType
SharednicApiImpl::read_sharednic_type_by_id(const std::string &name) {
  auto sharednic = get_cube(name);
  return sharednic->getType();

}




/**
* @brief   Update action by ID
*
* Update operation of resource: action*
*
* @param[in] name ID of name
* @param[in] value Action performed on the received packet (i.e., DROP, LINUX, or POLYCUBE; default: DROP)
*
* Responses:
*
*/
void
SharednicApiImpl::update_sharednic_action_by_id(const std::string &name, const SharednicActionEnum &value) {
  auto sharednic = get_cube(name);

  sharednic->setAction(value);
}




/**
* @brief   Update sharednic by ID
*
* Update operation of resource: sharednic*
*
* @param[in] name ID of name
* @param[in] value sharednicbody object
*
* Responses:
*
*/
void
SharednicApiImpl::update_sharednic_by_id(const std::string &name, const SharednicJsonObject &value) {
  auto sharednic = get_cube(name);

  sharednic->update(value);
}




/**
* @brief   Update sharednic by ID
*
* Update operation of resource: sharednic*
*
* @param[in] value sharednicbody object
*
* Responses:
*
*/
void
SharednicApiImpl::update_sharednic_list_by_id(const std::vector<SharednicJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}


#ifdef IMPLEMENT_POLYCUBE_GET_LIST
std::vector<nlohmann::fifo_map<std::string, std::string>> SharednicApiImpl::update_sharednic_list_by_id_get_list(const std::vector<SharednicJsonObject> &value) {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
}
#endif


/**
* @brief   Update loglevel by ID
*
* Update operation of resource: loglevel*
*
* @param[in] name ID of name
* @param[in] value Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE)
*
* Responses:
*
*/
void
SharednicApiImpl::update_sharednic_loglevel_by_id(const std::string &name, const SharednicLoglevelEnum &value) {
  auto sharednic = get_cube(name);

  sharednic->setLoglevel(value);
}




/**
* @brief   Update ports by ID
*
* Update operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
SharednicApiImpl::update_sharednic_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value) {
  auto sharednic = get_cube(name);
  auto ports = sharednic->getPorts(portsName);

  ports->update(value);
}




/**
* @brief   Update ports by ID
*
* Update operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
SharednicApiImpl::update_sharednic_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}


#ifdef IMPLEMENT_POLYCUBE_GET_LIST
std::vector<nlohmann::fifo_map<std::string, std::string>> SharednicApiImpl::update_sharednic_ports_list_by_id_get_list(const std::string &name, const std::vector<PortsJsonObject> &value) {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
}
#endif


}
}
}
}

