/**
* sharednic API
* Sharednic Service
*
* OpenAPI spec version: 2.0
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/netgroup-polito/swagger-codegen.git
* branch polycube
*/


/* Do not edit this file manually */

/*
* SharednicJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "PortsJsonObject.h"
#include <vector>
#include "polycube/services/cube.h"

using polycube::service::CubeType;

namespace io {
namespace swagger {
namespace server {
namespace model {

enum class SharednicLoglevelEnum {
  TRACE, DEBUG, INFO, WARN, ERR, CRITICAL, OFF
};
enum class SharednicActionEnum {
  DROP, LINUX, POLYCUBE
};

/// <summary>
///
/// </summary>
class  SharednicJsonObject : public JsonObjectBase {
public:
  SharednicJsonObject();
  virtual ~SharednicJsonObject();

  /////////////////////////////////////////////
  /// JsonObjectBase overrides

  void validateKeys() override;
  void validateMandatoryFields() override;
  void validateParams() override;

  nlohmann::json toJson() const override;
  void fromJson(nlohmann::json& json) override;

  static nlohmann::json helpKeys();
  static nlohmann::json helpElements();
  static nlohmann::json helpWritableLeafs();
  static nlohmann::json helpComplexElements();
  static std::vector<std::string> helpActions();
  /////////////////////////////////////////////
  /// SharednicJsonObject members

  /// <summary>
  /// Name of the sharednic service
  /// </summary>
  std::string getName() const;
  void setName(std::string value);
  bool nameIsSet() const;
  void unsetName();

  /// <summary>
  /// UUID of the Cube
  /// </summary>
  std::string getUuid() const;
  void setUuid(std::string value);
  bool uuidIsSet() const;
  void unsetUuid();

  /// <summary>
  /// Type of the Cube (TC, XDP_SKB, XDP_DRV)
  /// </summary>
  CubeType getType() const;
  void setType(CubeType value);
  bool typeIsSet() const;
  void unsetType();
  static std::string CubeType_to_string(const CubeType &value);
  static CubeType string_to_CubeType(const std::string &str);

  /// <summary>
  /// Defines the logging level of a service instance, from none (OFF) to the most verbose (TRACE)
  /// </summary>
  SharednicLoglevelEnum getLoglevel() const;
  void setLoglevel(SharednicLoglevelEnum value);
  bool loglevelIsSet() const;
  void unsetLoglevel();
  static std::string SharednicLoglevelEnum_to_string(const SharednicLoglevelEnum &value);
  static SharednicLoglevelEnum string_to_SharednicLoglevelEnum(const std::string &str);
  polycube::LogLevel getPolycubeLoglevel() const;
  /// <summary>
  /// Entry of the ports table
  /// </summary>
  const std::vector<PortsJsonObject>& getPorts() const;
  void addPorts(PortsJsonObject value);
  bool portsIsSet() const;
  void unsetPorts();

  /// <summary>
  /// Action performed on the received packet (i.e., DROP, LINUX, or POLYCUBE; default: DROP)
  /// </summary>
  SharednicActionEnum getAction() const;
  void setAction(SharednicActionEnum value);
  bool actionIsSet() const;
  void unsetAction();
  static std::string SharednicActionEnum_to_string(const SharednicActionEnum &value);
  static SharednicActionEnum string_to_SharednicActionEnum(const std::string &str);


protected:
  std::string m_name;
  bool m_nameIsSet;
  std::string m_uuid;
  bool m_uuidIsSet;
  CubeType m_type;
  bool m_typeIsSet;
  SharednicLoglevelEnum m_loglevel;
  bool m_loglevelIsSet;
  std::vector<PortsJsonObject> m_ports;
  bool m_portsIsSet;
  SharednicActionEnum m_action;
  bool m_actionIsSet;

  std::vector<std::string> allowedParameters_{ "name", "uuid", "type", "loglevel", "ports", "action" };
};

}
}
}
}

